#<<<<<<< HEAD
theme: jekyll-theme-dinky
#=======
# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Jahir Medina
full_name: Jahir Gilberth Medina Lopez
title: Student
email: contact@jahirmedina.com
website: jahirmedina.com

# Social links
twitter_username: jahirmedinacs
github_username:  jahirmedinacs
# dribbble_username: jekyll
facebook_username: jahirmedinacs
# flickr_username: jekyll
instagram_username: jahirmedinacs
linkedin_username: jahirmedinacs
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /assets/cv-front.jpg
about_content: | # this will include new lines to allow paragraphs
  Computer Science Student at National Unversity of Trujillo, ***Machine Learning Enthusiast*** and Scientific Computing Researcher in Progress

  Programming Languages
  
    |  P.L.  	| Habilities 	| Where 0  means:                      	| and my score:                                       	|
    |:------:	|:----------:	|-----------------------------------	|--------------------------------------------------------	|
    | Python 	|   95/100   	| Adding 2 Strings                  	| RSA Encryption with GUI Implementation                 	|
    |  C/C++ 	|   70/100   	| Sorting a List                    	| WAV Audio Compression with CLI                         	|
    |    R   	|   60/100   	| Plot a Histogram                  	| Create a MLP from Scratch                              	|
    |  Bash  	|   60/100   	| Execute 2 program using pipelines 	| Automatic AWS EC2 Conection with CLI and Verbos Option 	|
    |  SQL  	|   50/100   	| Create a View 	| Script for Transcription between Transaccional and Dimentional Database 	|

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# Academic Experience Section (and events)
# academic_experience_title: Academic Achievements and Events

# social responsibilities Section (and events)
social_responsibilities_title: Academic and Social Responsibilities

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
    i'm currently apoting to do a Master Degre in Economics, descition that was made during my exchange at ICMC - USP. 
    I do electronics, hardware assembling  and fixing during my spare time.
    Maybe i didnt mention the languages i spoke, so, see they below:

    - Spanish
    - Portuges
    - English
    - French
    - Learing : Mandarin

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
#>>>>>>> 0637ce672166658283db68ee11f5ce432f40d25c