#<<<<<<< HEAD
theme: jekyll-theme-dinky
#=======
# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Jahir Medina
full_name: Jahir Gilberth Medina Lopez
title: BsC. Computer Science / Informatics Engineer
email: contact@jahirmedina.com
# website: ghp.jahirmedina.com
phone_number: 
  - tag: WorldWide
    value: 12345294385
    whatsapp: true
    telegram: true
    telegramuser: jahirmedinacs_business
  - tag: Peru
    value: 51974453856
    whatsapp: true
    telegram: true
    telegramuser: jahirmedinacs_work
# Social links
#twitter_username: jahirmedinacs
github_username:  jahirmedinacs
# dribbble_username: jekyll
#facebook_username: jahirmedinacs
# flickr_username: jekyll
#instagram_username: jahirmedinacs
linkedin_username: jahirmedinacs
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
about_title: Brief Bio
about_profile_image: /assets/cv-firstplane.jpg
about_content: | # this will include new lines to allow paragraphs
  I see myself as a pragmatic, diligent, and multifaceted individual. From public speaking and political debate to microcontroller programming and task automation, I possess a diverse set of talents.
  
  Throughout my undergraduate education, I excelled and dedicated myself to a range of intellectual and political activities.
  
  The most remarkable moments during my undergraduate period were acchiving an academic exchange scholarship in which I learnt a lot about machine learning and winning national hackathons.
  
  Later, I was responsible for completing my bachellor thesis in a genetics and molecular biology lab, where my knowledge in server administration, cloud computing, and UNIX systems proved to be quite useful.
  
  Through hard work and commitment, I have had the opportunity to work for a variety of worldwide organizations, where I can continue to demonstrate the value of my work.


# Experience Section
experience_title: Work Experience #(Use this to override about experience section title)

# Programing Laguages Section
programing_languages_title: Programing Languages and Technical Tools #(Use this to override about experience section title)

# Projects Section
projects_title: Personal and Research Projects #(Use this to override about projects section title)

# Education Section
educaton_title: Education #(Use this to override about education section title)

# Languages
languages_title: Languages

# Academic Experience Section (and events)
academic_experience_title: Academic Achievements and Events

# social responsibilities Section (and events)
social_responsibilities_title: Academic and Social Responsibilities

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
# more_content: | # this will include new lines to allow paragraphs
#     i'm currently apoting to do a Master Degre in Economics, descition that was made during my exchange at ICMC - USP. 
#     I do electronics, hardware assembling  and fixing during my spare time.
#     Maybe i didnt mention the languages i spoke, so, see they below:

#     - Spanish
#     - Portuges
#     - English
#     - French
#     - Learing : Mandarin

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
#>>>>>>> 0637ce672166658283db68ee11f5ce432f40d25c